name: "Build and deploy CSS for BetterDiscord"

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build CSS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout theme
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Build CSS
        run: pnpm run build:bd

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          publish_dir: "./"