name: Lint

on:
  push:
    branches-ignore:
      - deploy
  pull_request:

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout theme
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
            node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
            version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Run linters
        run: pnpm run lint