name: Bundle and release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout theme
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Build and bundle theme into .asar
        run: pnpm run build:asar

      - name: Release bundled asar, json, and theme.css
        uses: ncipollo/release-action@v1
        with:
          artifacts: "bundle/*, *.theme.css"
          makeLatest: true
          generateReleaseNotes: true