name: Release for Replugged

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Checkout theme
        uses: actions/checkout@v2
        with:
          path: theme

      - name: Checkout Replugged
        uses: actions/checkout@v2
        with:
          repository: replugged-org/replugged
          path: replugged
          ref: v4.7.0

      - name: Link Replugged into theme
        run: |
          cd theme
          pnpm link ../replugged

      - name: Build and bundle Replugged
        run: |
          cd replugged
          pnpm install
          pnpm run bundle

      - name: Build and bundle theme into .asar
        run: |
          cd theme
          pnpm install
          pnpm run rp

      - name: Release theme .asar and .json
        uses: ncipollo/release-action@v1
        with:
          artifacts: theme/bundle/*
          makeLatest: true
          generateReleaseNotes: true